### ISSUE TITLE
add Path#getComputed relativeTo argument

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#103] opened 2012-10-04 15:48 UTC
Right now `Path.prototype.getComputed` only computes the position relative to its direct parent. It would be great if it could accept an argument that should serve as the target relative group/stage. So simply sugar `for (while (e.parent) ...`. If the parent was not found when the stage is encountered, silently ignore the argument (or log a warning if in debug mode...?).

**Comment by davidaurelio** [comment] 2012-10-05 11:41
This will be handled by the new signature

``` js
/**
 * @param {String} thing The thing to compute
 * @param {Matrix} [transform=null] A transformation to apply to all points prior to calculating dimensions.
 */
getComputed(thing, transform)
```

We need it anyways, it will come.

**Comment by davidaurelio** [comment] 2012-10-05 11:41
Not an exact duplicate of #74, but solving that will solve this one here. Closing

**Closed as completed by davidaurelio** 2012-10-05 11:41 UTC
Labels: enhancement
